ahoyapi: v2

usage: Decky plugin development commands
commands:
  # SETUP COMMANDS
  depsetup:
    usage: Install dependencies for basic setup
    cmd: ./.vscode/setup.sh

  pnpmsetup:
    usage: Setup pnpm and install dependencies
    cmd: |
      which pnpm && pnpm i

  updatefrontendlib:
    usage: Update @decky/ui (Decky Frontend Library)
    cmd: pnpm update @decky/ui --latest

  setup:
    usage: Complete setup - dependencies, pnpm, and update Decky Frontend Library
    cmd: |
      ahoy depsetup
      ahoy pnpmsetup
      ahoy updatefrontendlib

  settingscheck:
    usage: Check that settings.json has been created
    cmd: ./.vscode/config.sh

  # BUILD COMMANDS
  cli-build:
    usage: Build plugin with CLI
    cmd: ./.vscode/build.sh

  build:
    usage: Full build - setup, settings check, and build
    cmd: |
      ahoy setup
      ahoy settingscheck
      ahoy cli-build

  # DEPLOY COMMANDS
  chmodplugins:
    usage: Change permissions on plugins folder to prevent issues
    cmd: |
      ssh ${DECK_USER}@${DECK_IP} -p ${DECK_PORT} ${DECK_KEY} \
        "echo '${DECK_PASS}' | sudo -S chown ${DECK_USER} ${DECK_DIR}/homebrew/plugins/"

  copyzip:
    usage: Copy plugin zip to Steam Deck
    cmd: |
      ahoy chmodplugins
      rsync -azp --chmod=D0755,F0755 --rsh="ssh -p ${DECK_PORT} ${DECK_KEY}" \
        out/ ${DECK_USER}@${DECK_IP}:${DECK_DIR}/homebrew/plugins

  extractzip:
    usage: Extract plugin zip on Steam Deck
    cmd: |
      ssh ${DECK_USER}@${DECK_IP} -p ${DECK_PORT} ${DECK_KEY} \
        "echo ${DECK_PASS} | sudo -S mkdir -m 755 -p \"\$(echo \"${DECK_DIR}/homebrew/plugins/${PLUGIN_NAME}\" | sed \"s| |-|g\")\" && \
         echo ${DECK_PASS} | sudo -S chown ${DECK_USER}:${DECK_USER} \"\$(echo \"${DECK_DIR}/homebrew/plugins/${PLUGIN_NAME}\" | sed \"s| |-|g\")\" && \
         echo ${DECK_PASS} | sudo -S bsdtar -xzpf \"${DECK_DIR}/homebrew/plugins/${PLUGIN_NAME}.zip\" \
         -C \"\$(echo \"${DECK_DIR}/homebrew/plugins/${PLUGIN_NAME}\" | sed \"s| |-|g\")\" --strip-components=1 --fflags"

  deploy:
    usage: Deploy plugin to Steam Deck (copy and extract)
    cmd: |
      ahoy copyzip
      ahoy extractzip

  builddeploy:
    usage: Build and deploy plugin to Steam Deck
    cmd: |
      ahoy build
      ahoy deploy

  # UTILITY COMMANDS
  env:
    usage: Display all environment variables for debugging
    cmd: |
      echo "DECK_IP=${DECK_IP}"
      echo "DECK_PORT=${DECK_PORT}"
      echo "DECK_USER=${DECK_USER}"
      echo "DECK_PASS=${DECK_PASS}"
      echo "DECK_KEY=${DECK_KEY}"
      echo "DECK_DIR=${DECK_DIR}"
      echo "PLUGIN_NAME=${PLUGIN_NAME}"

  restartdecky:
    usage: Restart Decky Loader on Steam Deck
    cmd: |
      ssh ${DECK_USER}@${DECK_IP} -p ${DECK_PORT} ${DECK_KEY} \
        "echo '${DECK_PASS}' | sudo -S systemctl restart plugin_loader"
entrypoint:
  - bash
  - "-c"
  - "-e"
  - |
    [ -f .env ] && [ -s .env ] && export $(grep -v '^#' .env | xargs) && if [ -f .env.local ] && [ -s .env.local ]; then export $(grep -v '^#' .env.local | xargs); fi
    bash -e -c "$0" "$@"
  - '{{cmd}}'
  - '{{name}}'
